name: Build Verification

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.3.1'
      - name: Update hosts file
        run: echo '127.0.0.1 mssql mysql sfdc' | sudo tee --append /etc/hosts
      - name: pull images
        run: |
          docker pull glgresearch/sfdc-with-drakov:e04eea15
          docker pull microsoft/mssql-server-linux:2017-latest
          docker pull mysql:5.7.22
      - name: start docker containers
        run: docker-compose up --detach
      - name: make test
        env:
          CONNECTIONS: 'EPI_C_FILE EPI_C_MSSQL_O EPI_C_MSSQL EPI_C_MYSQL_BULK EPI_C_MYSQL EPI_C_RENDER EPI_C_SFDC EPI_C_SNOWFLAKE EPI_C_TIMESOUT NON_EXISTENT_SERVER'
          DEBUG: true
          DIFFTEST_QUIET: false
          ENABLE_TEMPLATE_ACLS: DISABLED
          EPI_C_FILE: '{"driver":"file","name":"file","config":{}}'
          EPI_C_MSSQL_O: '{"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}'
          EPI_C_MSSQL: '{"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}'
          EPI_C_MYSQL_BULK: '{"driver":"mysql","name":"mysql_bulk","type":"bulk","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}'
          EPI_C_MYSQL: '{"driver":"mysql","name":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}'
          EPI_C_RENDER: '{"driver":"render","name":"render","config":{}}'
          EPI_C_SFDC: '{"driver":"salesforce","name":"sfdc","config":{"userName":"","password":"","server":"http://sfdc"}}'
          EPI_C_SNOWFLAKE: '{"driver":"snowflake","name":"snowflake","config":{"account":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_ACCOUNT_ID }}", "warehouse":"EPIQUERY_PRODUCTION", "username":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_USERNAME }}", "password":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_PASSWORD }}"}}'
          EPI_C_TIMESOUT: '{"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433, "requestTimeout":1}}}'
          EPI_SCREAMER_URL: https://services.glgresearch.com/epi-screamer/epiquery
          EPI_TEST_SERVER: localhost
          FORKS: 1
          LOCK_DIRECTORY: ~/tmp
          NODE_ENV: development
          NON_EXISTENT_SERVER: '{"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}}'
          PORT: 8080
          TEMPLATE_DIRECTORY: ${{ github.workspace }}/difftest/templates/
        run: |
          TZ=UTC make start &
          ./bin/wait-for-epi
          DEBUG= make test
